# Generated by Django 5.2.5 on 2025-09-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_generating_response',
            field=models.BooleanField(default=False),
        ),
    ]
