# Generated by Django 5.2.5 on 2025-11-23 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='example_dialogue',
            field=models.TextField(blank=True, default='', help_text='<START> User: ... Char: ...'),
        ),
        migrations.AddField(
            model_name='character',
            name='first_message',
            field=models.TextField(blank=True, help_text='First message sent when chat starts.'),
        ),
        migrations.AddField(
            model_name='character',
            name='scenario',
            field=models.TextField(blank=True, default='', help_text='Default context/environment.'),
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(help_text='The core personality and visual description.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
