# Generated by Django 5.2.5 on 2025-09-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_is_generating_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='gemini_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
