# Generated by Django 5.2.5 on 2025-11-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_character_avatar_url_character_example_dialogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='affiliation',
            field=models.TextField(blank=True, default='', help_text="Character's organization or faction."),
        ),
    ]
