# Generated by Django 5.2.5 on 2025-09-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_gemini_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
