# Generated by Django 5.2.5 on 2025-09-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_gemini_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='response_guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
