# Generated by Django 5.2.5 on 2025-11-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_character_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_context',
            field=models.TextField(blank=True, help_text='Additional context for this specific session'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='enable_search',
            field=models.BooleanField(default=False, help_text='Allow AI to search internet'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='output_language',
            field=models.CharField(default='Simplified Chinese', help_text='Language for AI responses', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_persona',
            field=models.CharField(default='Sensei', help_text="User's role in this chat", max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='world_time',
            field=models.CharField(blank=True, help_text='e.g. Dec 11, 2025 6:30PM', max_length=100, null=True),
        ),
    ]
