# Generated by Django 5.2.5 on 2025-09-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_gemini_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background_document',
            field=models.FileField(blank=True, null=True, upload_to='character_docs/'),
        ),
        migrations.AddField(
            model_name='character',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='character_images/'),
        ),
    ]
