# Generated by Django 5.2.5 on 2025-11-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_current_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='current_context',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='enable_search',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='additional_context',
            field=models.TextField(blank=True, default='', help_text='Extra instructions for this session'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='enable_web_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='output_language',
            field=models.CharField(blank=True, default='Simplified Chinese', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user_persona',
            field=models.TextField(blank=True, default='', help_text="User's role or identity in this chat"),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='world_time',
            field=models.CharField(blank=True, default='Current time', max_length=100),
        ),
    ]
