# Generated by Django 5.2.5 on 2025-09-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_file_url_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='file_url',
        ),
        migrations.AddField(
            model_name='character',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='character_files/'),
        ),
    ]
