# Generated by Django 5.2.5 on 2025-09-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_character_background_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='background_document',
        ),
        migrations.AddField(
            model_name='character',
            name='gemini_file_ref',
            field=models.CharField(blank=True, help_text='Reference ID for the file uploaded to Gemini API', max_length=255, null=True),
        ),
    ]
