# Generated by Django 5.2.5 on 2025-09-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_character_image_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
