# Generated by Django 5.2.5 on 2025-09-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_file_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='response_guidelines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
