# Generated by Django 5.2.5 on 2025-09-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_character_file_url_character_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gemini_file_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
