# Generated by Django 5.2.5 on 2025-09-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_character_background_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='gemini_file_ref',
        ),
        migrations.CreateModel(
            name='CharacterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('gemini_file_ref', models.CharField(help_text='Reference ID for the file uploaded to Gemini API', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_files', to='chat.character')),
            ],
        ),
    ]
