# Generated by Django 5.2.5 on 2025-12-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatsession_current_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='gemini_file_uri',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_uri',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='output_language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user_persona',
            field=models.TextField(blank=True, default='Li, An Overwhelmed Underwriting Manager', help_text="User's role or identity in this chat"),
        ),
    ]
