# Generated by Django 5.2.5 on 2025-09-11 02:46

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_character_gemini_file_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='disabled_states',
            field=models.JSONField(default=chat.models.get_default_disabled_states),
        ),
    ]
