# Generated by Django 5.2.5 on 2025-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_character_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
