# Generated by Django 5.2.5 on 2025-09-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_character_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='requirement',
            field=models.TextField(default="=== RESPONSE GUIDELINES ===\nInstructions:\n- Respond consistently with your character's traits and background\n- Maintain character voice throughout the conversation\n- Be engaging and responsive to user input\n- Stay true to your established character"),
        ),
    ]
