# Generated by Django 5.2.5 on 2026-04-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_character_system_prompt_preview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoulPatch',
        ),
        migrations.DeleteModel(
            name='SoulDocument',
        ),
    ]
