# Generated by Django 5.2.5 on 2026-08-17 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_text_role_assignments(apps, schema_editor):
    """每个用户把现有默认（或第一个）模型配置映射为 text 角色分配。"""
    ModelConfiguration = apps.get_model('chat', 'ModelConfiguration')
    ModelRoleAssignment = apps.get_model('chat', 'ModelRoleAssignment')
    for config in ModelConfiguration.objects.all().order_by('-is_default', 'id'):
        ModelRoleAssignment.objects.get_or_create(
            user_id=config.user_id,
            role='text',
            defaults={'model_config_id': config.id},
        )


def unseed_text_role_assignments(apps, schema_editor):
    ModelRoleAssignment = apps.get_model('chat', 'ModelRoleAssignment')
    ModelRoleAssignment.objects.filter(role='text').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_long_term_memory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('text', 'Text chat'), ('image', 'Image understanding'), ('audio', 'Audio understanding'), ('video', 'Video understanding')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.AlterModelOptions(
            name='modelconfiguration',
            options={'ordering': ['name', 'id']},
        ),
        migrations.RenameIndex(
            model_name='charactermemoryitem',
            new_name='chat_charac_charact_8bf5b3_idx',
            old_name='chat_charactermem_char_section',
        ),
        migrations.RenameIndex(
            model_name='charactermemoryitem',
            new_name='chat_charac_charact_a6893d_idx',
            old_name='chat_charactermem_char_updated',
        ),
        migrations.RenameIndex(
            model_name='memoryauditlog',
            new_name='chat_memory_charact_d48735_idx',
            old_name='chat_memoryauditl_char_time',
        ),
        migrations.AddField(
            model_name='modelroleassignment',
            name='model_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='chat.modelconfiguration'),
        ),
        migrations.AddField(
            model_name='modelroleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='modelroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_model_role_assignment_per_user'),
        ),
        migrations.RunPython(seed_text_role_assignments, unseed_text_role_assignments),
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='is_default',
        ),
        migrations.AddField(
            model_name='characterknowledgeasset',
            name='media_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='media_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='characterknowledgeasset',
            name='attachment_kind',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='charactermemoryitem',
            name='section',
            field=models.CharField(help_text='Free-form section name picked and reused by the model. Composite index on (character, section) is created below.', max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment_kind',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='attachment_kind',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='modelconfiguration',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('openai_compatible', 'OpenAI Compatible'), ('anthropic', 'Anthropic')], default='openai_compatible', max_length=32),
        ),
    ]
