# Generated by Django 5.2.5 on 2026-08-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_chatsession_is_title_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='enable_web_search',
            field=models.BooleanField(blank=True, default=None, help_text="Per-character web search override. None follows the user's global default.", null=True),
        ),
    ]
