# Generated by Django 5.2.5 on 2026-08-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_character_tts_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='tts_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
