# Generated by Django 5.2.5 on 2026-08-25 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_alter_character_tts_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TtsServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_provider', models.CharField(blank=True, choices=[('genie', 'Genie-TTS (GPT-SoVITS ONNX)'), ('gptsovits', 'GPT-SoVITS api_v2'), ('indextts', 'IndexTTS')], default='', max_length=16)),
                ('genie_url', models.CharField(blank=True, default='', max_length=500)),
                ('gptsovits_url', models.CharField(blank=True, default='', max_length=500)),
                ('indextts_url', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts_service_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='TtsVoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engine', models.CharField(choices=[('genie', 'Genie-TTS (GPT-SoVITS ONNX)'), ('gptsovits', 'GPT-SoVITS api_v2'), ('indextts', 'IndexTTS')], default='genie', max_length=16)),
                ('model_version', models.CharField(blank=True, default='', help_text='v2 / v2pro / v2proplus / v4，空=未指定', max_length=16)),
                ('language', models.CharField(blank=True, default='', help_text='模型语言 zh/jp/en/ko', max_length=8)),
                ('voice_name', models.CharField(blank=True, default='', help_text='genie 侧音色键，空则取 ONNX 目录名', max_length=100)),
                ('onnx_model_dir', models.CharField(blank=True, default='', help_text='genie 通道：convert_to_onnx 输出目录', max_length=500)),
                ('ref_audio_path', models.CharField(blank=True, default='', help_text='参考音频服务器路径（绝对路径或 MEDIA_ROOT 相对路径）', max_length=500)),
                ('ref_audio_text', models.TextField(blank=True, default='')),
                ('ref_audio_language', models.CharField(blank=True, default='', max_length=8)),
                ('conversion_status', models.CharField(blank=True, choices=[('ready', 'Ready'), ('pending', 'Pending conversion'), ('converting', 'Converting'), ('failed', 'Conversion failed')], default='', max_length=16)),
                ('conversion_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('conversion_error', models.TextField(blank=True, default='')),
                ('source_ckpt_path', models.CharField(blank=True, default='', help_text='上传的 T2S .ckpt（转换源）', max_length=500)),
                ('source_pth_path', models.CharField(blank=True, default='', help_text='上传的 VITS .pth（转换源）', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_voice_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_tts_voice_model_name_per_user')],
            },
        ),
    ]
