# Generated by Django 5.2.5 on 2026-08-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_migrate_character_tts_to_voice_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsvoicemodel',
            name='emotions',
            field=models.JSONField(blank=True, default=list, help_text='情感组列表：[{name, ref_audio_path, ref_audio_text, ref_audio_language}]'),
        ),
    ]
