# Generated by Django 5.2.5 on 2026-08-28 18:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_ttsvoicemodel_emotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('session/created', 'Session created'), ('user/message', 'User message'), ('assistant/message', 'Assistant message'), ('compaction/summary', 'Compacted-history summary')], max_length=40)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat.character')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat.chatsession')),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['chat_session', 'seq'], name='chat_chatev_chat_se_04ea03_idx'), models.Index(fields=['character', 'seq'], name='chat_chatev_charact_ec1c34_idx')],
                'constraints': [models.UniqueConstraint(fields=('chat_session', 'seq'), name='unique_chat_event_seq_per_session')],
            },
        ),
    ]
