# Generated by Django 5.2.5 on 2026-08-28 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_backfill_chat_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='characterknowledgeasset',
            name='upload_event_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Id of the asset/uploaded AssetEvent this row projects from.', null=True),
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('asset/uploaded', 'Uploaded (staged, unattached)'), ('asset/attached', 'Attached to character'), ('asset/detached', 'Detached from character'), ('asset/expired', 'Expired unattached upload')], max_length=40)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_events', to='chat.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='chat_assete_user_id_bf3b7e_idx'), models.Index(fields=['character', 'event_type'], name='chat_assete_charact_5db186_idx')],
            },
        ),
    ]
