# Generated by Django 5.2.5 on 2026-08-29 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_characterknowledgeasset_upload_event_id_assetevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDraftJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceling', 'Canceling'), ('canceled', 'Canceled')], default='running', max_length=16)),
                ('stage', models.CharField(blank=True, default='', max_length=32)),
                ('progress_done', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True, default='')),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('checkpoint', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_draft_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'status'], name='chat_charac_user_id_2ba48f_idx')],
            },
        ),
    ]
