# Generated by Django 5.2.5 on 2026-08-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_characterknowledgeasset_upload_event_id_assetevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TtsAudioOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='本次合成的文本')),
                ('emotion', models.CharField(blank=True, default='', help_text='情感名，空=默认参考音频', max_length=64)),
                ('provider', models.CharField(blank=True, default='', help_text='实际使用的 TTS provider', max_length=16)),
                ('audio', models.FileField(upload_to='tts_outputs/%Y/%m/')),
                ('content_type', models.CharField(blank=True, default='audio/wav', max_length=100)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('first_byte_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tts_audio_outputs', to='chat.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_audio_outputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', '-id'], name='chat_ttsaud_user_id_3ffe0d_idx'), models.Index(fields=['character', '-id'], name='chat_ttsaud_charact_1ff6ec_idx')],
            },
        ),
    ]
