# Generated by Django 5.2.5 on 2026-08-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0042_ttsaudiooutput'),
        ('chat', '0043_characterdraftjob_content_fingerprint_and_more'),
    ]

    operations = [
    ]
