# Generated by Django 5.2.5 on 2026-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0047_userprofile_location_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='raw_reasoning',
            field=models.TextField(blank=True, default='', help_text="Dual-thinking protocol: the model's objective raw chain of thought (RAW_REASONING block), kept separate from the in-character inner monologue in `thinking`."),
        ),
    ]
