# Generated by Django 5.2.5 on 2026-08-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0048_message_raw_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='steps',
            field=models.JSONField(blank=True, default=list, help_text='Full ReAct timeline: ordered [{kind: thinking, text, raw_text} | {kind: tool, tool, arguments}] steps across every loop round.'),
        ),
    ]
