# Generated by Django 5.2.5 on 2026-09-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0049_message_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('streaming', 'streaming'), ('interrupted', 'interrupted')], default='', help_text="Incremental-persistence lifecycle: 'streaming' while the reply is being written (content/thinking/tool calls land in real time); '' once the turn completed; 'interrupted' when the turn failed but kept its partial content. A row still 'streaming' after the page was closed means the stream died mid-way — the UI renders it as an incomplete reply.", max_length=16),
        ),
    ]
