"""
Django settings for prismate project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Reading .env file
environ.Env.read_env(str(BASE_DIR / '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',  # Add TokenAuthentication
    'strawberry.django',
    'chat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Disabled for GraphQL API
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'chat.middleware.DevAutoLoginMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prismate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prismate.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DATABASE_NAME', default='prismate'),
        'USER': env('DATABASE_USER', default='postgres'),
        'PASSWORD': env('DATABASE_PASSWORD', default=''),
        'HOST': env('DATABASE_HOST', default='localhost'),
        'PORT': env('DATABASE_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'chat.authentication.CsrfExemptSessionAuthentication',
    ],
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3002",
])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3002",
])

# Celery settings
REDIS_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Memory v2 §3.1: dev ergonomics for the per-turn long-term-memory task.
# ALWAYS_EAGER (DEBUG default): .delay() executes in-process, so chatting
#   without a Celery worker still writes memory.
# MEMORY_SYNC_INLINE_FALLBACK: when eager is off and the broker rejects the
#   enqueue, run the task body in-process instead of dropping it silently.
#   Keep False in production so a dead broker never blocks reply finalization.
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=DEBUG)
MEMORY_SYNC_INLINE_FALLBACK = env.bool('MEMORY_SYNC_INLINE_FALLBACK', default=False)

# Event-sourced chat history compaction (v0.1.4): when the estimated history
# tokens of a session cross threshold_ratio × context_window, a Celery task
# condenses the oldest active events into a ``compaction/summary`` event.
# The full log (and the UI history) stays intact; only the model-facing
# derived prompt is compacted.
COMPACTION_ENABLED = env.bool('COMPACTION_ENABLED', default=True)
COMPACTION_THRESHOLD_RATIO = env.float('COMPACTION_THRESHOLD_RATIO', default=0.7)
COMPACTION_RETAIN_RATIO = env.float('COMPACTION_RETAIN_RATIO', default=0.3)
COMPACTION_MIN_HISTORY_TOKENS = env.int('COMPACTION_MIN_HISTORY_TOKENS', default=8000)
COMPACTION_MIN_RETAIN_TOKENS = env.int('COMPACTION_MIN_RETAIN_TOKENS', default=4000)
COMPACTION_SUMMARY_MAX_TOKENS = env.int('COMPACTION_SUMMARY_MAX_TOKENS', default=1024)
# When the broker rejects the enqueue, run the compaction body in-process
# instead of dropping it. Keep False in production (a dead broker must never
# block reply finalization).
COMPACTION_INLINE_FALLBACK = env.bool('COMPACTION_INLINE_FALLBACK', default=False)

# Event-sourced character-reference assets (v0.1.4): staged uploads live as
# asset/uploaded AssetEvents with a TTL; unattached staging files are
# reclaimed lazily (on each upload) and by `manage.py clean_stale_uploads`.
ASSET_UPLOAD_TTL_DAYS = env.int('ASSET_UPLOAD_TTL_DAYS', default=7)

DEV_AUTO_LOGIN_ENABLED = env.bool('DEV_AUTO_LOGIN_ENABLED', default=DEBUG)
DEV_AUTO_LOGIN_USERNAME = env('DEV_AUTO_LOGIN_USERNAME', default='demo_user')
DEV_AUTO_LOGIN_EMAIL = env('DEV_AUTO_LOGIN_EMAIL', default='demo@example.com')

# Realtime voice input (ASR). The package dependency is optional and lives in
# backend/requirements-asr.txt; with it missing the endpoints degrade to a
# readable readiness hint instead of erroring.
# 默认 sense_voice：sherpa-onnx + SenseVoiceSmall int8（Owl Meeting 模型 1 同款，
# 非自回归、纯 CPU 低延迟、原生简体+标点；模型需运行
# backend/scripts/download_asr_models.py 下载）。
# 回滚旧引擎：ASR_PROVIDER=faster_whisper（ASR_MODEL/DEVICE/COMPUTE_TYPE 仍生效）。
ASR_PROVIDER = env('ASR_PROVIDER', default='sense_voice')
ASR_NUM_THREADS = env.int('ASR_NUM_THREADS', default=2)
SENSE_VOICE_DIR = BASE_DIR / 'ml_models' / 'asr' / 'sense-voice'
# faster_whisper 档位（回滚用）：base 是延迟实测后的默认档（短句中位 ~1.4s，
# 见 docs/benchmarks/latency-v0.1.3.md）。
ASR_MODEL = env('ASR_MODEL', default='base')
ASR_DEVICE = env('ASR_DEVICE', default='cpu')
ASR_COMPUTE_TYPE = env('ASR_COMPUTE_TYPE', default='int8')

# Realtime voice reply (TTS). Engines run as standalone HTTP services;
# Django only talks to them. genie = Genie-TTS (GPT-SoVITS ONNX, CPU by
# default — start scripts/genie_server.py with --device cuda for NVIDIA GPU;
# supports v2/v2ProPlus converted characters); gptsovits = official
# api_v2 (all four model versions, best deployed on a GPU); indextts reserved.
TTS_PROVIDER = env('TTS_PROVIDER', default='genie')
TTS_GENIE_URL = env('TTS_GENIE_URL', default='http://127.0.0.1:8050')
# 每个角色的模型目录/参考音频/语言是角色属性，只在角色编辑页「语音模型」
# 区块配置（Character.tts_config），不设全局环境变量兜底。
TTS_GPTSOVITS_URL = env('TTS_GPTSOVITS_URL', default='http://127.0.0.1:9880')
TTS_GPTSOVITS_TEXT_LANG = env('TTS_GPTSOVITS_TEXT_LANG', default='zh')
TTS_GPTSOVITS_REF_AUDIO_PATH = env('TTS_GPTSOVITS_REF_AUDIO_PATH', default='')
TTS_GPTSOVITS_PROMPT_TEXT = env('TTS_GPTSOVITS_PROMPT_TEXT', default='')
TTS_GPTSOVITS_PROMPT_LANG = env('TTS_GPTSOVITS_PROMPT_LANG', default='zh')
TTS_INDEXTTS_URL = env('TTS_INDEXTTS_URL', default='')
TTS_INDEXTTS_TEXT_FIELD = env('TTS_INDEXTTS_TEXT_FIELD', default='text')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
